name: ehentter
description: "A new Flutter project."
publish_to: "none"
version: 0.4.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^17.1.0
  get_it: ^9.2.0
  meta: ^1.17.0
  shared_preferences: ^2.5.4
  dio: ^5.9.1
  html: ^0.15.6
  waterfall_flow: ^3.1.1
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
